version: 2

sources:
    - name: staging
      database: dazzling-pier-338723
      schema: trips_data_all_us


      tables:
        - name: green_tripdata_external_table
        - name: yellow_tripdata_external_table